service: go-dynamodb-stream-s3

custom:
  dynamodb:
    tableName: users
    batchSize: 100
    batchWindow: 10
    startingPosition: LATEST # Process new records that are added to the stream
    maximumRetryAttempts: 10
  firehose:
    deliveryStreamName: mystream
    bufferInterval: 60
    bufferSize: 1
  s3:
    bucketName: go-metadata-pipeline-test
    path: dynamodb/

provider: 
  name: aws
  runtime: go1.x
  timeout: 60

  region: eu-central-1

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:DescribeStream"
        - "dynamodb:GetRecords"
        - "dynamodb:GetShardIterator"
        - "dynamodb:ListStreams"
      Resource:
        - Fn::Join:
            - ""
            - - "arn:aws:dynamodb:"
              - Ref: "AWS::Region"
              - ":"
              - Ref: "AWS::AccountId"
              - ":table/${self:custom.dynamodb.tableName}"
    - Effect: "Allow"
      Action:
        - "firehose:PutRecordBatch"
      Resource:
        - Fn::Join:
            - ""
            - - "arn:aws:firehose:"
              - Ref: "AWS::Region"
              - ":"
              - Ref: "AWS::AccountId"
              - ":deliverystream/${self:custom.firehose.deliveryStreamName}"

package:
  exclude:
    - ./**
  include:
    - ./bin/**

functions:
  # function is invoked when one of the following conditions is met: 
  # the payload size reaches 6MB, the Batch Window reaches its maximum value, 
  # or the Batch Size reaches its maximum value
  dynamoStreamHandler:
    handler: bin/main
    environment:
      STREAM_NAME: ${self:custom.firehose.deliveryStreamName}
    events:
      - stream:
          type: dynamodb
          arn:
            Fn::GetAtt: [DynamoDBTable, StreamArn]
          batchSize: ${self:custom.dynamodb.batchSize}
          batchWindow: ${self:custom.dynamodb.batchWindow}
          startingPosition: ${self:custom.dynamodb.startingPosition}
          maximumRetryAttempts: ${self:custom.dynamodb.maximumRetryAttempts}
  firehoseTransformer:
    handler: bin/transform

resources: 
  Resources:
    DynamoDBTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.dynamodb.tableName}
        AttributeDefinitions:
          - AttributeName: email
            AttributeType: S
        KeySchema:
          - AttributeName: email
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES
    
    KinesisFirehoseStream:
      Type: AWS::KinesisFirehose::DeliveryStream
      Properties:
        DeliveryStreamName: ${self:custom.firehose.deliveryStreamName}
        DeliveryStreamType: DirectPut
        ExtendedS3DestinationConfiguration: 
          BucketARN: arn:aws:s3:::${self:custom.s3.bucketName}
          Prefix: ${self:custom.s3.path}
          RoleARN: !GetAtt DeliveryRole.Arn 
          BufferingHints:
            IntervalInSeconds: ${self:custom.firehose.bufferInterval}
            SizeInMBs: ${self:custom.firehose.bufferSize}
          CompressionFormat: UNCOMPRESSED # GZIP
    
    DeliveryRole:
      Type: AWS::IAM::Role
      Properties:
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Sid: ""
              Effect: Allow
              Principal:
                Service: firehose.amazonaws.com
              Action: "sts:AssumeRole"
              Condition:
                StringEquals:
                  "sts:ExternalId": !Ref "AWS::AccountId"

    DeliveryPolicy:
      Type: AWS::IAM::Policy
      Properties:
        PolicyName: firehose_delivery_policy
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - "s3:AbortMultipartUpload"
                - "s3:GetBucketLocation"
                - "s3:GetObject"
                - "s3:ListBucket"
                - "s3:ListBucketMultipartUploads"
                - "s3:PutObject"
              Resource:
                - !Sub "arn:aws:s3:::${self:custom.s3.bucketName}"
                - !Sub "arn:aws:s3:::${self:custom.s3.bucketName}*"
        Roles:
          - !Ref DeliveryRole
