service: go-dynamodb-stream-s3

custom:
  tableName:
    users: "users"

provider: 
  name: aws
  runtime: go1.x
  timeout: 30

  region: eu-central-1

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:DescribeStream"
        - "dynamodb:GetRecords"
        - "dynamodb:GetShardIterator"
        - "dynamodb:ListStreams"
      Resource:
        - Fn::Join:
            - ""
            - - "arn:aws:dynamodb:"
              - Ref: "AWS::Region"
              - ":"
              - Ref: "AWS::AccountId"
              - ":table/${self:custom.tableName.users}"

package:
  exclude:
    - ./**
  include:
    - ./bin/**

functions:
  stream:
    handler: bin/main
    events:
      - stream:
          type: dynamodb
          arn:
            Fn::GetAtt: [usersTable, StreamArn]

resources: 
  Resources:
    usersTable: 
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: users
        AttributeDefinitions:
          - AttributeName: email
            AttributeType: S
        KeySchema:
          - AttributeName: email
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES
